let currentUser=null;let attendanceBuffer=[];
const $=id=>document.getElementById(id);
function getLS(k,d=[]){return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}
function setLS(k,v){localStorage.setItem(k,JSON.stringify(v))}
async function addDocSafe(col,data){data.createdAt=new Date().toISOString(); if(firebaseReady) await db.collection(col).add(data); let arr=getLS(col); arr.push({...data,id:Date.now()+Math.random()}); setLS(col,arr)}
async function getAllSafe(col){ if(firebaseReady){let s=await db.collection(col).get();return s.docs.map(d=>({id:d.id,...d.data()}));} return getLS(col); }
async function init(){ if(!getLS('users').length){setLS('users',[{role:'admin',name:'Default Admin',username:'admin',password:'admin123',department:'All',year:'All'}]);}
 $('attDate').valueAsDate=new Date(); showPage('loginPage'); renderUsers(); if('serviceWorker'in navigator) navigator.serviceWorker.register('service-worker.js');}
function showPage(id){document.querySelectorAll('main>section').forEach(s=>s.classList.add('hide'));$(id).classList.remove('hide')}
async function login(){let role=$('loginRole').value,u=$('loginUsername').value.trim(),p=$('loginPassword').value.trim();let users=await getAllSafe('users');let found=users.find(x=>x.role===role&&x.username===u&&x.password===p);if(!found){alert('Wrong username/password');return}currentUser=found;if(role==='admin'){showPage('adminPage');renderUsers()}if(role==='teacher'){showPage('teacherPage');$('teacherInfo').innerHTML=`Logged in: <b>${found.name||found.username}</b> | Subject: <b>${found.subject||''}</b>`;$('attSubject').value=found.subject||'';$('attDept').value=found.department||'';$('attYear').value=found.year||''}if(role==='cr'){showPage('crPage');$('crDept').value=found.department||'';$('crYear').value=found.year||''}if(role==='hod'){showPage('hodPage');$('hodDept').value=found.department||'';$('hodYear').value=found.year||''}}
function logout(){currentUser=null;showPage('loginPage')}
async function saveUser(){let data={role:$('newRole').value,name:$('newName').value,username:$('newUsername').value.trim(),password:$('newPassword').value.trim(),department:$('newDepartment').value,year:$('newYear').value,subject:$('newSubject').value};if(!data.username||!data.password)return alert('Username and password required');await addDocSafe('users',data);alert('User saved');renderUsers()}
async function renderUsers(){let el=$('usersList');if(!el)return;let users=await getAllSafe('users');el.innerHTML='<div class="table"><table><tr><th>Role</th><th>Name</th><th>Username</th><th>Dept</th><th>Year</th><th>Subject</th></tr>'+users.map(u=>`<tr><td>${u.role}</td><td>${u.name||''}</td><td>${u.username}</td><td>${u.department||''}</td><td>${u.year||''}</td><td>${u.subject||''}</td></tr>`).join('')+'</table></div>'}
async function saveStudent(){let photo='';let f=$('sPhoto').files[0]; if(f){photo=await new Promise(r=>{let fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)})}let data={name:$('sName').value,roll:$('sRoll').value.trim(),department:$('sDept').value,year:$('sYear').value,section:$('sSection').value,photo,phone:$('sPhone').value,parentPhone:$('sParent').value,email:$('sEmail').value,address:$('sAddress').value};if(!data.name||!data.roll)return alert('Name and Roll No required');await addDocSafe('students',data);alert('Student saved')}
async function savePost(){await addDocSafe('posts',{department:$('postDept').value,year:$('postYear').value,text:$('postText').value,type:'timetable'});alert('Posted to CR page')}
async function saveEvent(){await addDocSafe('events',{title:$('eventTitle').value,date:$('eventDate').value,details:$('eventDetails').value});alert('Event uploaded')}
async function saveHodNotice(){await addDocSafe('posts',{department:$('hodDept').value,year:$('hodYear').value,text:$('hodNotice').value,type:'hod_notice'});alert('Notice uploaded')}
async function loadStudentsForAttendance(){let students=(await getAllSafe('students')).filter(s=>(!$('attDept').value||s.department===$('attDept').value)&&(!$('attYear').value||s.year===$('attYear').value));attendanceBuffer=students.map(s=>({roll:s.roll,name:s.name,status:'Present'}));$('attendanceList').innerHTML=attendanceBuffer.map((s,i)=>`<div class="row"><span><b>${s.roll}</b> - ${s.name}</span><select onchange="attendanceBuffer[${i}].status=this.value"><option>Present</option><option>Absent</option></select></div>`).join('')||'No students found'}
async function saveAttendance(){if(!currentUser||currentUser.role!=='teacher')return alert('Only subject staff can mark attendance');let data={teacher:currentUser.username,subject:$('attSubject').value,department:$('attDept').value,year:$('attYear').value,date:$('attDate').value,hour:$('attHour').value,records:attendanceBuffer};await addDocSafe('attendance',data);alert('Attendance saved')}
async function crLoad(){let dept=$('crDept').value,year=$('crYear').value;let posts=(await getAllSafe('posts')).filter(p=>(!dept||p.department===dept)&&(!year||p.year===year));$('crPosts').innerHTML=posts.map(p=>`<p class="note"><b>${p.type}</b><br>${p.text}</p>`).join('')||'No posts';let st=(await getAllSafe('students')).filter(s=>(!dept||s.department===dept)&&(!year||s.year===year));$('crStudents').innerHTML=st.map(s=>`<span class="badge">${s.roll} - ${s.name}</span>`).join('')||'No students';let at=(await getAllSafe('attendance')).filter(a=>(!dept||a.department===dept)&&(!year||a.year===year));$('crAttendance').innerHTML=at.map(a=>`<p>${a.date} | ${a.hour} | ${a.subject} | Marked by ${a.teacher}</p>`).join('')||'No attendance'}
function calcPercent(records,roll){let total=0,p=0;records.forEach(a=>(a.records||[]).forEach(r=>{if(r.roll===roll){total++;if(r.status==='Present')p++}}));return total?Math.round(p/total*100):0}
async function hodLoad(){let dept=$('hodDept').value,year=$('hodYear').value;let st=(await getAllSafe('students')).filter(s=>(!dept||s.department===dept)&&(!year||s.year===year));let at=(await getAllSafe('attendance')).filter(a=>(!dept||a.department===dept)&&(!year||a.year===year));$('hodReport').innerHTML='<div class="table"><table id="reportTable"><tr><th>Roll</th><th>Name</th><th>Department</th><th>Year</th><th>Attendance %</th></tr>'+st.map(s=>`<tr><td>${s.roll}</td><td>${s.name}</td><td>${s.department}</td><td>${s.year}</td><td>${calcPercent(at,s.roll)}%</td></tr>`).join('')+'</table></div>'}
function downloadExcel(){let html=document.getElementById('reportTable')?.outerHTML;if(!html)return alert('Load report first');let blob=new Blob([html],{type:'application/vnd.ms-excel'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='attendance-report.xls';a.click()}
function downloadPDF(){window.print()}
async function studentCheck(){let roll=$('checkRoll').value.trim();let at=await getAllSafe('attendance');let rows=[];at.forEach(a=>(a.records||[]).forEach(r=>{if(r.roll===roll)rows.push({...a,status:r.status})}));let per=calcPercent(at,roll);$('studentResult').innerHTML=`<h3>Attendance: ${per}%</h3>`+rows.map(r=>`<p>${r.date} | ${r.hour} | ${r.subject} | <b>${r.status}</b></p>`).join('')||'No records found'}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hide')});$('installBtn')?.addEventListener('click',async()=>{if(deferredPrompt)deferredPrompt.prompt()});
document.addEventListener('DOMContentLoaded',init);
