const $=id=>document.getElementById(id);let currentRole=null,currentSubject="";const slots=["9-10","10-11","11-12","12-1","2-3","3-4"];
const defUsers=[{role:"admin",name:"Main Admin",username:"admin",password:"admin123",dept:"All",year:"All"}];
function get(k){return JSON.parse(localStorage.getItem(k)||"[]")}function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function init(){if(!localStorage.getItem('users'))set('users',defUsers);$('aDate')?.setAttribute('value',new Date().toISOString().slice(0,10));$('cDate')?.setAttribute('value',new Date().toISOString().slice(0,10));}
async function saveData(col,obj,id=null){const ft=window.firebaseTools;if(ft?.firebaseReady){if(id)await ft.setDoc(ft.doc(ft.db,col,id),obj);else await ft.addDoc(ft.collection(ft.db,col),obj)}let arr=get(col); if(id){let i=arr.findIndex(x=>x.id===id); if(i>=0)arr[i]=obj; else arr.push(obj)}else arr.push({...obj,id:Date.now()+Math.random().toString(16).slice(2)}); set(col,arr)}
async function readData(col){const ft=window.firebaseTools;if(ft?.firebaseReady){try{const snap=await ft.getDocs(ft.collection(ft.db,col));return snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn(e)}}return get(col)}
window.show=id=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active')}
window.goLogin=role=>{show('login');$('loginRole').value=role}
window.showDashboard=()=>{show('dashboard');['adminMenu','hodMenu','crMenu'].forEach(id=>$(id).classList.add('hidden'));$(currentRole+'Menu')?.classList.remove('hidden');$('dashTitle').innerText=currentRole?.toUpperCase()+" Dashboard"}
window.login=async()=>{let role=$('loginRole').value,u=$('loginUser').value.trim(),p=$('loginPass').value.trim();let users=await readData('users');let ok=users.find(x=>x.role===role&&x.username===u&&x.password===p);if(!ok)return alert('Wrong username/password');currentRole=role;$('logoutBtn').classList.remove('hidden');showDashboard()}
$('logoutBtn').onclick=()=>{currentRole=null;$('logoutBtn').classList.add('hidden');show('home')}
window.saveStudent=async()=>{let file=$('sProfile').files[0];let photo='';if(file)photo=await new Promise(res=>{let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)});let s={name:$('sName').value,roll:$('sRoll').value.trim(),dept:$('sDept').value,year:$('sYear').value,photo,phone:$('sPhone').value,parentPhone:$('sParent').value,email:$('sEmail').value,address:$('sAddress').value,createdAt:new Date().toISOString()};if(!s.name||!s.roll)return alert('Name and Roll No required');await saveData('students',s,s.roll);alert('Student saved')}
window.saveUser=async()=>{let u={role:$('uRole').value,name:$('uName').value,username:$('uUsername').value.trim(),password:$('uPassword').value.trim(),subject:$('uSubject').value.trim(),dept:$('uDept').value,year:$('uYear').value,createdAt:new Date().toISOString()};if(!u.username||!u.password)return alert('Username/password required');await saveData('users',u);alert('Login saved in Firebase/localStorage')}
window.openAttendance=async()=>{let sub=$('gateSubject').value.trim(),u=$('gateUser').value.trim(),p=$('gatePass').value.trim();let users=await readData('users');let ok=users.find(x=>x.role==='staff'&&x.subject.toLowerCase()===sub.toLowerCase()&&x.username===u&&x.password===p);if(!ok)return alert('Subject staff login wrong');currentSubject=sub;show('attendancePage')}
window.loadAttendanceStudents=async()=>{let list=(await readData('students')).filter(s=>s.dept===$('aDept').value&&s.year===$('aYear').value);$('attendanceList').innerHTML=list.length?`<table class="table"><tr><th>Roll</th><th>Name</th><th>Present</th><th>Absent</th></tr>${list.map(s=>`<tr data-roll="${s.roll}" data-name="${s.name}"><td>${s.roll}</td><td>${s.name}</td><td><input type="radio" name="att_${s.roll}" value="Present" checked></td><td><input type="radio" name="att_${s.roll}" value="Absent"></td></tr>`).join('')}</table>`:'No students found'}
window.saveAttendance=async()=>{let rows=[...document.querySelectorAll('#attendanceList tr[data-roll]')];if(!rows.length)return alert('Load students first');let rec={date:$('aDate').value,dept:$('aDept').value,year:$('aYear').value,slot:$('aSlot').value,subject:currentSubject,postedBy:$('gateUser').value,createdAt:new Date().toISOString(),students:rows.map(r=>({roll:r.dataset.roll,name:r.dataset.name,status:document.querySelector(`input[name="att_${r.dataset.roll}"]:checked`).value}))};await saveData('attendance',rec);alert('Attendance saved')}
window.loadStudentsView=async()=>{let d=$('vDept')?.value||'B.Sc Computer Science',y=$('vYear')?.value||'1st Year';let list=(await readData('students')).filter(s=>s.dept===d&&s.year===y);$('studentsTable').innerHTML=`<table class="table"><tr><th>Photo</th><th>Name</th><th>Roll</th><th>Dept</th><th>Year</th><th>Phone</th><th>Parent</th><th>Email</th><th>Address</th></tr>${list.map(s=>`<tr><td>${s.photo?`<img class="profile" src="${s.photo}">`:''}</td><td>${s.name}</td><td>${s.roll}</td><td>${s.dept}</td><td>${s.year}</td><td>${s.phone||''}</td><td>${s.parentPhone||''}</td><td>${s.email||''}</td><td>${s.address||''}</td></tr>`).join('')}</table>`}
window.loadCrAttendance=async()=>{let d=$('cDept').value,y=$('cYear').value,dt=$('cDate').value;let att=(await readData('attendance')).filter(a=>a.dept===d&&a.year===y&&a.date===dt);$('crAttendanceTable').innerHTML=`<table class="table"><tr><th>Subject</th><th>Hour</th><th>Status</th><th>Posted By</th></tr>${slots.map(sl=>{let a=att.find(x=>x.slot===sl);return `<tr><td>${a?.subject||'-'}</td><td>${sl}</td><td>${a?'<span class="status-present">Posted</span>':'<span class="status-absent">Not Posted</span>'}</td><td>${a?.postedBy||'-'}</td></tr>`}).join('')}</table>`}
window.saveTimetable=async()=>{await saveData('timetables',{dept:$('ttDept').value,year:$('ttYear').value,text:$('ttText').value,createdAt:new Date().toISOString()});alert('Timetable posted')}
window.loadTimetable=async()=>{let t=await readData('timetables');$('timetableResult').innerHTML=t.length?t.reverse().map(x=>`<div class="hint"><b>${x.dept} - ${x.year}</b><br><pre>${x.text}</pre></div>`).join(''):'No timetable posted'}
window.saveEvent=async()=>{await saveData('events',{title:$('eTitle').value,date:$('eDate').value,details:$('eDetails').value,createdAt:new Date().toISOString()});alert('Event uploaded')}
window.loadEvents=async()=>{let e=await readData('events');$('eventsResult').innerHTML=e.length?e.reverse().map(x=>`<div class="hint"><b>${x.title}</b> - ${x.date}<br>${x.details}</div>`).join(''):'No events'}
function calc(records,roll=null){let map={};records.forEach(a=>a.students?.forEach(s=>{if(roll&&s.roll!==roll)return;let key=s.roll+'|'+s.name+'|'+a.subject;if(!map[key])map[key]={roll:s.roll,name:s.name,subject:a.subject,total:0,present:0};map[key].total++;if(s.status==='Present')map[key].present++}));return Object.values(map).map(x=>({...x,percent:x.total?Math.round(x.present/x.total*100):0}))}
window.checkStudentAttendance=async()=>{let roll=$('pRoll').value.trim();let rec=(await readData('attendance')).filter(a=>a.dept===$('pDept').value&&a.year===$('pYear').value);let rows=calc(rec,roll);$('portalResult').innerHTML=rows.length?`<table class="table"><tr><th>Subject</th><th>Total</th><th>Present</th><th>%</th></tr>${rows.map(r=>`<tr><td>${r.subject}</td><td>${r.total}</td><td>${r.present}</td><td>${r.percent}%</td></tr>`).join('')}</table>`:'No attendance found'}
window.loadReports=async()=>{let rec=(await readData('attendance')).filter(a=>a.dept===$('rDept').value&&a.year===$('rYear').value&&(!$('rSubject').value||a.subject.toLowerCase()===$('rSubject').value.toLowerCase()));let rows=calc(rec);window.reportRows=rows;$('reportTable').innerHTML=`<table class="table" id="rep"><tr><th>Roll</th><th>Name</th><th>Subject</th><th>Total Hours</th><th>Present</th><th>Percentage</th></tr>${rows.map(r=>`<tr><td>${r.roll}</td><td>${r.name}</td><td>${r.subject}</td><td>${r.total}</td><td>${r.present}</td><td>${r.percent}%</td></tr>`).join('')}</table>`}
window.downloadPDF=()=>{let {jsPDF}=window.jspdf;let doc=new jsPDF();doc.text('Madha Attendance Report',10,10);(window.reportRows||[]).forEach((r,i)=>doc.text(`${r.roll} ${r.name} ${r.subject} ${r.percent}%`,10,20+i*8));doc.save('madha-attendance-report.pdf')}
window.downloadExcel=()=>{let ws=XLSX.utils.json_to_sheet(window.reportRows||[]);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');XLSX.writeFile(wb,'madha-attendance-report.xlsx')}
window.showAttendanceGate=()=>show('attendanceGate');
init();
